### ISSUE TITLE
Breaks on `from collections import MutableMapping` in Python 3.10

### ISSUE THREAD

**Issue by ssoj13** [seperman/dotobject#3]
Just importing dotobject in Python 3.10 (fresh WSL Ubuntu) causes an error, since MutableMapping is supposed to be imported from collections.abc  now and support for old behavior was dropped in Python 3.9.

Basically right now [Redisworks](https://github.com/seperman/redisworks) is broken (and suffering from the same problem by itself)  because of that and cannot be used out of the box.

**Comment by seperman** [comment]
HI, just fixed it.
